import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import '../styles/globals.css';
=======
import "./globals.css";
>>>>>>> f94b0e1 (fix: atualiza)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<<<<<<< HEAD
 
=======

>>>>>>> f94b0e1 (fix: atualiza)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 p-0 w-full h-full`}
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> f94b0e1 (fix: atualiza)
      >
        {children}
      </body>
    </html>
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> f94b0e1 (fix: atualiza)
